#!/usr/bin/env python
import os, sys
import gtk

from odml.tools.gui import Editor

def main(filename=None):
    Editor.register_stock_icons()
    editor = Editor.Editor(filename=filename)
    gtk.main()

if __name__ == '__main__':
    try: # this works only on linux
        from ctypes import *
        libc = cdll.LoadLibrary("libc.so.6")
        res = libc.prctl (15, 'odMLEditor', 0, 0, 0)
    except:
        pass
    from optparse import OptionParser
    parser = OptionParser()
    (options, args) = parser.parse_args()
    main(filename=args[0]) if len(args) > 0 else main()
    
