#!/usr/bin/env python
import os, sys
import gtk

from odml import gui

if __name__ == '__main__':
    try: # this works only on linux
        from ctypes import *
        libc = cdll.LoadLibrary("libc.so.6")
        res = libc.prctl (15, 'odMLEditor', 0, 0, 0)
    except:
        pass
    from optparse import OptionParser
    parser = OptionParser()
    (options, args) = parser.parse_args()
    gui.main(filenames=args)
    gtk.main()
    
